### ISSUE TITLE
What's the datasource that you are looking at right now?

### ISSUE THREAD

**Issue by jlmayorga** [minoad/lisdcovidanalysis#1]
@minoad, Are you only looking at LISD reported cases, or are you looking at something else?

**Comment by minoad** [comment]
Still going through setup at the moment.

Im going to try and find a restful API, but if not will have to use beautiful soup to scrape.  This is where I am starting.  https://www.leanderisd.org/covid19dashboard/

**Comment by jlmayorga** [comment]
Most of the data that is displayed in the Dashboard comes from a google spreadsheet that is public

https://docs.google.com/spreadsheets/d/1tntE5QMCliVMqLfy1SyeKEZz-Uefk2coQjo1eJB5Zb8/edit#gid=0

I already have some python code that fetches de data from the Google API and populates a Pandas DataFrame, I haven't done much with it but it may help.

I will try to figure out where they are getting the historic data from.

**Comment by jlmayorga** [comment]
The spreadsheet that I referenced is the one used by the Dashboard, I believe that the one that you have in the README file is generated by someone by manually exporting the data from the Dashboard page and importing it into a google spreadsheet.

**Comment by jlmayorga** [comment]
I submitted a PR with the code that I have, let me know if it helps
